// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Load env from backend root, where .env is kept.
dotenv.config({ path: path.resolve(__dirname, "..", ".env") });

export default defineConfig({
  schema: "src/prisma/schema.prisma",
  migrations: {
    path: "src/prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
